apiVersion: v1
kind: Template
metadata:
  annotations:
    description: |-
      m8cmp-portal是M8Cloud极量云门户网站，此模板通过源代码构建来部署m8cmp-portal
  name: m8cmp-portal-sourcecode-build-template
  namespace: openshift
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: m8cmp-portal-git-secret
  data:
    username: d2FuZ3BlbmdjaGVuZw==
    password: d2Y5MjkxMThmeQ==
  type: kubernetes.io/basic-auth
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: m8cmp-portal
    name: m8cmp-portal
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: m8cmp-portal
    name: m8cmp-portal
  spec:
    nodeSelector:
      region: infra
    output:
      to:
        kind: ImageStreamTag
        name: m8cmp-portal:latest
    source:
      git:
        ref: master
        uri: ${SOURCE_REPOSITORY_URL}
      sourceSecret:
        name: m8cmp-portal-git-secret
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: PACKAGE_COMMAND
          value: cnpm run build && rm -fr src node_modules build config gifs static
            .git .npminstall_tarball .postcssrc.js LICENSE README*.md favicon.ico
            index.html  package-lock.json && cnpm install express
        from:
          kind: ImageStreamTag
          name: nodejs8-cnpm:latest
          namespace: openshift
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: m8cmp-portal
    name: m8cmp-portal
  spec:
    replicas: 1
    selector:
      deploymentconfig: m8cmp-portal
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: m8cmp-portal
          deploymentconfig: m8cmp-portal
      spec:
        containers:
        - env:
          - name: NPM_RUN
            value: serviceRun
          imagePullPolicy: Always
          name: m8cmp-portal
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 512m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        nodeSelector:
          region: infra
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - m8cmp-portal
        from:
          kind: ImageStreamTag
          name: m8cmp-portal:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: m8cmp-portal
    name: m8cmp-portal
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 1122
    selector:
      deploymentconfig: m8cmp-portal
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: m8cmp-portal
    name: m8cmp-portal
  spec:
    host: portal.${SUBDOMAIN}
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: m8cmp-portal
      weight: 100
    wildcardPolicy: None
parameters:
- description: "m8cmp-web源代码仓库地址"
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: http://172.17.10.187/cmp/m8cmp-portal.git
- description: "可拉取m8cmp-web仓库地址权限的账号"
  displayName: Git Username
  name: USERNAME
  required: true
  value: wangpengcheng
- description: "可拉取m8cmp-web仓库地址权限的密码"
  displayName: Git Password
  name: PASSWORD
  required: true
  value: wf929118fy
- description: "m8cloud子域名"
  displayName: subdomain
  name: SUBDOMAIN
  required: true
  value: test.com
