apiVersion: v1
kind: Template
metadata:
  annotations:
    description: |-
      m8cmp-portal是M8Cloud极量云门户网站，此模板通过镜像来部署m8cmp-portal
  name: m8cmp-portal-images-deploy-template
  namespace: openshift
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: m8cmp-portal
    name: m8cmp-portal
  spec:
    replicas: 1
    selector:
      deploymentconfig: m8cmp-portal
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: m8cmp-portal
          deploymentconfig: m8cmp-portal
      spec:
        containers:
        - env:
          - name: NPM_RUN
            value: serviceRun
          image: ${PORTAL_IMAGES_REGISTRY_URL}
          imagePullPolicy: Always
          name: m8cmp-portal
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 512m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        nodeSelector:
          region: infra
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: m8cmp-portal
    name: m8cmp-portal
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 1122
    selector:
      deploymentconfig: m8cmp-portal
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: m8cmp-portal
    name: m8cmp-portal
  spec:
    host: portal.${SUBDOMAIN}
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: m8cmp-portal
      weight: 100
    wildcardPolicy: None
parameters:
- description: "m8cmp-portal镜像仓库地址"
  displayName: m8cmp-portal images registry url
  name: PORTAL_IMAGES_REGISTRY_URL
  required: true
  value: dockerhub.csg.com:5000/m8cloud/m8cmp-portal:latest
- description: "m8cloud子域名"
  displayName: subdomain
  name: SUBDOMAIN
  required: true
  value: test.com
