apiVersion: v1
kind: Template
metadata:
  annotations:
    description: |-
      m8site-map是中通服软件科技有限公司网站导航地图，此模板通过源代码构建来部署m8site-map
  name: m8site-map-sourcecode-build-template
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: m8site-map
    name: m8site-map-git-secret
  data:
    username: d2FuZ3BlbmdjaGVuZw==
    password: d2Y5MjkxMThmeQ==
  type: kubernetes.io/basic-auth
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: site-map
    name: site-map
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: site-map:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: ${SOURCE_REPOSITORY_URL}
      sourceSecret:
        name: m8site-map-git-secret
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: PACKAGE_COMMAND
          value: cnpm install express
        from:
          kind: ImageStreamTag
          name: nodejs8-cnpm:latest
          namespace: openshift
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: site-map
    name: site-map
  spec:
    replicas: 1
    selector:
      deploymentconfig: site-map
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: site-map
          deploymentconfig: site-map
      spec:
        containers:
        - imagePullPolicy: Always
          name: site-map
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - site-map
        from:
          kind: ImageStreamTag
          name: site-map:latest
          namespace: m8default
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: site-map
    name: site-map
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: site-map
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: site-map
    name: site-map
  spec:
    host: site-map.${SUBDOMAIN}
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: site-map
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: site-map
    name: site-map
  spec:
    lookupPolicy:
      local: false
parameters:
- description: "m8cmp-web源代码仓库地址"
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: http://172.17.10.187/product/site_map.git
- description: "可拉取m8cmp-web仓库地址权限的账号"
  displayName: Git Username
  name: USERNAME
  required: true
  value: wangpengcheng
- description: "可拉取m8cmp-web仓库地址权限的密码"
  displayName: Git Password
  name: PASSWORD
  required: true
  value: wf929118fy
- description: "m8cloud子域名"
  displayName: subdomain
  name: SUBDOMAIN
  required: true
  value: test.com
